const funds=[
{id:'equity',name:'Equity Growth Fund',type:'Equity',assets:50000000,liabilities:1760000,units:4820000,previous:9.9841},
{id:'bond',name:'Global Bond Fund',type:'Fixed Income',assets:34000000,liabilities:1850000,units:3180000,previous:10.0412},
{id:'property',name:'Real Estate Fund',type:'Real Estate',assets:24000000,liabilities:1650000,units:2210000,previous:10.1054}];
const pages=[['overview','Overview'],['workspace','NAV Workspace'],['reconciliation','Reconciliation'],['exceptions','Exceptions'],['approvals','Approvals'],['reports','Reporting'],['audit','Audit Trail']];
const fresh=f=>({input:{assets:f.assets,liabilities:f.liabilities,units:f.units,previous:f.previous},phase:'idle',exceptions:[],approvals:[],reports:[],events:[]});
const storageKey='navcalc-demo-v4';let data;
try{const saved=JSON.parse(localStorage.getItem(storageKey));if(saved?.version===4&&funds.every(f=>saved.cycles?.[f.id]))data=saved}catch{}
data ||= {version:4,fund:'equity',cycles:Object.fromEntries(funds.map(f=>[f.id,fresh(f)]))};
let page='overview',drawer=false,modal=null,query='',formError='';
const fund=()=>funds.find(f=>f.id===data.fund),cycle=()=>data.cycles[data.fund];
const nav=c=>(c.input.assets-c.input.liabilities)/c.input.units;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:4}).format(n);
const num=n=>new Intl.NumberFormat('en-US').format(n);
const html=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const open=c=>c.exceptions.filter(e=>e.status==='Open');
const calculated=c=>!['idle','imported'].includes(c.phase);
const ready=c=>calculated(c)&&!open(c).length&&c.phase!=='released';
const stage=c=>c.phase==='released'?'Released':c.approvals.length===2?'Approved · release pending':open(c).length?'Needs exception review':c.phase==='idle'?'Not started':c.phase==='imported'?'Inputs imported':c.approvals.length?'First approval complete':'Ready for approval';
function save(){try{localStorage.setItem(storageKey,JSON.stringify(data))}catch{}}
function log(c,action,detail){c.events.unshift({time:new Date().toISOString(),action,detail});save()}
function go(p){page=p;drawer=false;modal=null;query='';formError='';render();window.scrollTo(0,0)}
function notify(message){let el=document.getElementById('toast');el.textContent=message;el.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.hidden=true,3500)}
function importData(){let c=cycle();if(c.phase!=='idle')return;c.phase='imported';log(c,'Demo inputs imported','Fictional fund inputs loaded');render()}
function saveInputs(form){let values=Object.fromEntries(['assets','liabilities','units','previous'].map(k=>[k,Number(form.elements[k].value)]));if(!Object.values(values).every(Number.isFinite)||values.assets<=values.liabilities||values.liabilities<0||values.units<=0||values.previous<=0){formError='Assets must exceed liabilities. Units and previous NAV must be greater than zero.';render();return}let c=cycle();c.input=values;c.phase='imported';c.exceptions=[];c.approvals=[];c.reports=[];log(c,'Valuation inputs changed','Previous controls and approvals cleared');formError='';render();notify('Inputs saved. Run calculation again.')}
function run(){let c=cycle();if(c.phase!=='imported')return;let move=(nav(c)/c.input.previous-1)*100;c.exceptions=[{id:'PRICE-01',name:'Missing market price',detail:'Illustrative security price needs review.',status:'Open',note:''}];if(Math.abs(move)>1)c.exceptions.push({id:'MOVE-01',name:'NAV movement above 1% tolerance',detail:`Movement of ${move.toFixed(2)}% requires review.`,status:'Open',note:''});c.phase='review';log(c,'NAV calculated and validated',`${money(nav(c))} per unit; ${c.exceptions.length} review item(s)`);render();notify('Review the exceptions before approval.')}
function resolve(id,note){let c=cycle(),e=c.exceptions.find(x=>x.id===id);if(!e||e.status!=='Open'||c.phase==='released')return;if(!note.trim()){formError='Write a resolution note before completing review.';render();return}e.status='Resolved';e.note=note.trim();log(c,'Exception resolved',`${id}: ${e.note}`);modal=null;formError='';render();notify(open(c).length?'Other exceptions still need review.':'All exceptions cleared. Approval is available.')}
function approve(){let c=cycle();if(!ready(c)||c.approvals.length>=2)return;let role=c.approvals.length?'Fund controller':'Fund accountant';c.approvals.push({role,time:new Date().toISOString()});log(c,`${role} approval recorded`,money(nav(c)));render();notify(`${role} approval recorded.`)}
function release(){let c=cycle();if(!ready(c)||c.approvals.length!==2)return;c.phase='released';log(c,'NAV released',`${money(nav(c))} per unit`);render();notify('Demo NAV released. Reports unlocked.')}
function report(type){let c=cycle();if(c.phase!=='released')return;if(!c.reports.includes(type)){c.reports.push(type);log(c,'Report generated',type)}modal={type:'report',name:type};render()}
function controls(c){if(!calculated(c))return [['Input validation','Pending','Run calculation'],['Market price review','Pending','Run calculation'],['Movement review','Pending','Run calculation']];let p=c.exceptions.find(e=>e.id==='PRICE-01'),m=c.exceptions.find(e=>e.id==='MOVE-01');return [['Input validation','Passed','Assets, liabilities and units valid'],['Market price review',p.status==='Resolved'?'Reviewed':'Review',p.note||p.detail],['Movement review',m?(m.status==='Resolved'?'Reviewed':'Review'):'Passed',m?(m.note||m.detail):'Within 1% tolerance']]}
function csvRows(type){let c=cycle();if(type==='audit')return [['Time','Action','Detail'],...c.events.map(e=>[e.time,e.action,e.detail])];if(type==='Exceptions')return [['ID','Exception','Status','Resolution'],...c.exceptions.map(e=>[e.id,e.name,e.status,e.note])];if(type==='Controls')return [['Control','Status','Evidence'],...controls(c)];return [['Fund','Assets','Liabilities','Net assets','Units','Previous NAV','NAV per unit','Approvals'],[fund().name,c.input.assets,c.input.liabilities,c.input.assets-c.input.liabilities,c.input.units,c.input.previous,nav(c).toFixed(4),c.approvals.map(x=>x.role).join(' & ')]]}
function download(type){let c=cycle();if(type!=='audit'&&(c.phase!=='released'||!c.reports.includes(type)))return;let text='\uFEFF'+csvRows(type).map(row=>row.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`navcalc-demo-${type.toLowerCase()}.csv`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const button=(label,action,attrs='')=>`<button type="button" data-action="${action}" ${attrs}>${label}</button>`;
const panel=(body,cls='')=>`<section class="panel ${cls}">${body}</section>`;
const head=(title,description)=>`<div class="head"><div><h1>${title}</h1><p>${description}</p></div><span class="demo-label">Fictional data · concept</span></div>`;
const badge=(label,kind='')=>`<span class="status ${kind}">${html(label)}</span>`;
function overview(){let c=cycle();return head('NAV operations overview','A connected journey from valuation inputs to release')+panel(`<div><small class="eyebrow">INTERACTIVE NAV WORKFLOW</small><h2>Make the NAV close easier to understand.</h2><p>Follow one fictional fund through calculation, exception review, two approvals and reporting. Actions on every page share the same state.</p>${button(c.phase==='idle'?'Start demo cycle →':'Continue cycle →','workspace')}</div><div class="hero-side"><small>SELECTED FUND</small><h3>${html(fund().name)}</h3><small>CURRENT STAGE</small><b>${html(stage(c))}</b></div>`,'hero')+`<div class="cards">${[['NAV / unit',calculated(c)?money(nav(c)):'—','Based on current inputs'],['Open exceptions',open(c).length,'Approval gate'],['Approvals',`${c.approvals.length} / 2`,'Separate sign-offs'],['Generated reports',c.reports.length,'After release']].map(([a,b,d])=>panel(`<small>${a}</small><strong>${b}</strong><span>${d}</span>`,'metric')).join('')}</div><div class="two">${panel('<h3>Manual handoffs</h3><ol><li>Collect spreadsheet inputs</li><li>Reconcile sources manually</li><li>Track breaks through messages</li><li>Coordinate approval and reports</li></ol>')}${panel('<h3>Connected workflow concept</h3><ol><li>Load controlled inputs</li><li>Calculate and validate</li><li>Document each exception review</li><li>Approve, release and export evidence</li></ol>')}</div>`}
function workspace(){let c=cycle(),v=calculated(c)?(nav(c)/c.input.previous-1)*100:0;return head('NAV workspace',`${html(fund().name)} · current demo cycle`)+panel(`<div class="section-head"><div><h3>1 · Data intake</h3><p>Adjust illustrative values, then run controls. Edits invalidate older approvals.</p></div>${c.phase==='idle'?button('Import demo data','import'):badge('Data loaded','good')}</div>${c.phase!=='idle'?`<form id="inputs" class="fields">${[['assets','Assets ($)'],['liabilities','Liabilities ($)'],['units','Units outstanding'],['previous','Previous NAV / unit ($)']].map(([k,l])=>`<label>${l}<input name="${k}" type="number" step="any" min="0" required value="${c.input[k]}"></label>`).join('')}<button type="submit">Save values & reset calculation</button></form>`:''}${formError&&!modal?`<p class="error" role="alert">${html(formError)}</p>`:''}`)+panel(`<div class="section-head"><div><h3>2 · Calculate and validate</h3><p>Illustrative arithmetic: (assets − liabilities) ÷ units. This is not NAVCalc's proprietary engine.</p></div>${c.phase==='imported'?button('Run calculation & controls','run'):calculated(c)?badge('Controls completed','good'):badge('Awaiting data')}</div>${calculated(c)?`<div class="calc"><span>Assets <b>${money(c.input.assets)}</b></span><span>Liabilities <b>− ${money(c.input.liabilities)}</b></span><span>Net assets <b>${money(c.input.assets-c.input.liabilities)}</b></span><span>Units <b>${num(c.input.units)}</b></span><strong>NAV PER UNIT ${money(nav(c))}</strong></div><p>Previous ${money(c.input.previous)} · movement ${v>=0?'+':''}${v.toFixed(2)}%</p>`:''}`)+panel(`<div class="section-head"><div><h3>3 · Review and release</h3><p>${calculated(c)?`${open(c).length} unresolved item(s); ${c.approvals.length}/2 approvals; ${html(stage(c))}.`:'Run controls to begin review.'}</p></div>${button(open(c).length?'Review exceptions →':'Open approvals →',open(c).length?'exceptions':'approvals')}</div>`) }
function reconciliation(){let c=cycle();return head('Reconciliation & controls','Live results for the selected fund')+panel(`<div class="table-scroll"><table><thead><tr><th>Control</th><th>Status</th><th>Evidence</th></tr></thead><tbody>${controls(c).map(([n,s,d])=>`<tr><td><b>${html(n)}</b></td><td>${badge(s,['Passed','Reviewed'].includes(s)?'good':s==='Review'?'warn':'')}</td><td>${html(d)}</td></tr>`).join('')}</tbody></table></div>`)+panel(`<div class="section-head"><div><h3>Review items</h3><p>The demo always surfaces one missing price to show how a control blocks approval.</p></div>${button('Open exceptions →','exceptions')}</div>`) }
function exceptionsPage(){let c=cycle();return head('Exception register','Review notes connect exceptions to the audit trail')+(calculated(c)?`<div class="exception-grid">${c.exceptions.map(e=>panel(`<div class="section-head"><div><small>${e.id}</small><h3>${html(e.name)}</h3></div>${badge(e.status,e.status==='Resolved'?'good':'warn')}</div><p>${html(e.detail)}</p>${e.note?`<div class="resolution"><b>Resolution:</b> ${html(e.note)}</div>`:button('Review & resolve',`resolve:${e.id}`)}`)).join('')}</div>`:panel(`<h3>No controls run yet</h3><p>Run a calculation to surface illustrative review items.</p>${button('Go to workspace →','workspace')}`))}
function approvals(){let c=cycle(),allowed=ready(c);return head('Approvals & release','Exception review is required before either sign-off')+panel(`<div class="section-head"><div><h2>${html(stage(c))}</h2><p>${calculated(c)?`${money(nav(c))} per unit · ${open(c).length} open exceptions`:'No calculated NAV yet.'}</p></div>${badge(c.phase==='released'?'Released':open(c).length?'Blocked':allowed?'Ready':'Pending',c.phase==='released'||allowed?'good':open(c).length?'warn':'')}</div>${controls(c).map(([n,s])=>`<div class="check"><span>${html(n)}</span>${badge(s,['Passed','Reviewed'].includes(s)?'good':s==='Review'?'warn':'')}</div>`).join('')}${open(c).length?'<p class="warning">Resolve all exceptions to unlock approvals.</p>':''}`)+`<div class="two">${panel(`<small>FIRST SIGN-OFF</small><h3>Fund accountant</h3><p>Illustrative reviewer step.</p>${c.approvals.length?badge('Approved','good'):button('Approve as accountant','approve',allowed?'':'disabled')}`)}${panel(`<small>SECOND SIGN-OFF</small><h3>Fund controller</h3><p>Requires the first approval.</p>${c.approvals.length===2?badge('Approved','good'):button('Approve as controller','approve',allowed&&c.approvals.length===1?'':'disabled')}`)}</div>`+panel(`<div class="section-head"><div><h3>Release NAV</h3><p>Requires clear controls and two approvals. Reporting unlocks after release.</p></div>${c.phase==='released'?badge('Released','good'):button('Release approved NAV','release',allowed&&c.approvals.length===2?'':'disabled')}</div>`)}
function reports(){let c=cycle();return head('Report center','Reports use the released cycle and export real CSV rows')+(c.phase!=='released'?panel(`<h3>Reporting is locked</h3><p>Resolve exceptions, record both approvals and release the NAV.</p>${button('Open approvals →','approvals')}`):`<div class="report-grid">${['NAV summary','Controls','Exceptions'].map(t=>panel(`<small>REPORT</small><h3>${t}</h3><p>${c.reports.includes(t)?'Generated from current cycle':'Ready to generate'}</p>${button(c.reports.includes(t)?'Preview':'Generate & preview',`report:${t}`)} ${c.reports.includes(t)?button('Download CSV',`csv:${t}`,'class="secondary"'):''}`)).join('')}</div>`)}
function audit(){let c=cycle();return head('Audit trail','Events created by your actions for this fund')+panel(`<div class="section-head"><div><h3>${c.events.length} recorded events</h3><p>Inputs, calculation, resolutions, approvals and reports appear here.</p></div>${button('Export audit CSV','csv:audit',c.events.length?'class="secondary"':'disabled')}</div><div class="event-list">${c.events.length?c.events.map(e=>`<div><time>${new Date(e.time).toLocaleString()}</time><span><b>${html(e.action)}</b><small>${html(e.detail)}</small></span></div>`).join(''):'<p>No events yet. Start a demo cycle.</p>'}</div>`)}
const views={overview,workspace,reconciliation,exceptions:exceptionsPage,approvals,reports,audit};
function reportModal(type){let rows=csvRows(type);return `<h2>${html(type)} · preview</h2><p>${html(fund().name)} · fictional data</p><div class="table-scroll"><table><thead><tr>${rows[0].map(x=>`<th>${html(x)}</th>`).join('')}</tr></thead><tbody>${rows.slice(1).map(row=>`<tr>${row.map(x=>`<td>${html(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="dialog-actions">${button('Close','close','class="secondary"')}${button('Download CSV',`csv:${type}`)}</div>`}
function modalView(){if(!modal)return '';let body=modal.type==='reset'?`<h2>Reset selected fund?</h2><p>This removes its inputs, exceptions, approvals, reports and audit events from this browser.</p><div class="dialog-actions">${button('Cancel','close','class="secondary"')}${button('Reset cycle','confirm-reset')}</div>`:modal.type==='resolve'?`<h2>${html(cycle().exceptions.find(e=>e.id===modal.id)?.name||'Exception')}</h2><p>Record what was reviewed in this fictional example.</p><form id="resolution"><label>Review note<textarea name="note" required placeholder="Describe the review or correction"></textarea></label>${formError?`<p class="error" role="alert">${html(formError)}</p>`:''}<div class="dialog-actions">${button('Cancel','close','class="secondary"')}<button type="submit">Record resolution</button></div></form>`:reportModal(modal.name);return `<div class="backdrop" data-action="close"><div class="dialog" role="dialog" aria-modal="true" aria-label="${modal.type}">${body}</div></div>`}
function searchResults(){let q=query.trim().toLowerCase(),hits=[];if(q){pages.forEach(([id,n])=>{if(n.toLowerCase().includes(q))hits.push([id,n,'Page'])});funds.forEach(f=>{if((f.name+' '+f.type).toLowerCase().includes(q))hits.push([`fund:${f.id}`,f.name,'Fund'])});cycle().exceptions.forEach(e=>{if((e.id+' '+e.name).toLowerCase().includes(q))hits.push(['exceptions',e.name,e.status])})}return hits.length?hits.map(([act,label,kind])=>`<button data-action="${act}"><small>${html(kind)}</small>${html(label)}</button>`).join(''):'<p>No matching page, fund or exception.</p>'}
function renderSearch(){let el=document.getElementById('search-results');el.hidden=!query.trim();if(!el.hidden)el.innerHTML=searchResults()}
function render(){document.getElementById('app').innerHTML=`<div class="layout"><aside class="sidebar ${drawer?'open':''}"><div class="brand"><span class="mark">N</span><span><b>NAVCalc</b><small>Interactive concept</small></span></div><nav aria-label="Main navigation">${pages.map(([id,name])=>`<button data-action="${id}" class="nav-item ${id===page?'selected':''}">${name}</button>`).join('')}</nav><div class="sidebar-foot"><b>CONCEPT ONLY</b><p>Fictional data. Actual workflow needs NAVCalc validation.</p></div></aside>${drawer?'<button class="shade" data-action="menu" aria-label="Close navigation"></button>':''}<div class="main"><header class="topbar"><button class="menu-toggle" data-action="menu" aria-label="Toggle navigation" aria-expanded="${drawer}">☰</button><div class="searchbox"><label for="search">⌕</label><input id="search" autocomplete="off" placeholder="Search pages, funds, exceptions" value="${html(query)}"></div><select id="fund-select" aria-label="Select demo fund">${funds.map(f=>`<option value="${f.id}" ${f.id===data.fund?'selected':''}>${html(f.name)}</option>`).join('')}</select><span class="concept">● Interactive concept</span></header><div id="search-results" class="search-results" hidden></div><main class="content">${views[page]()}<footer><span>Public concept · illustrative arithmetic · fictional data</span>${button('Reset selected fund','reset','class="text-button"')}</footer></main></div></div><div id="toast" role="status" hidden></div>${modalView()}`;renderSearch()}
document.addEventListener('click',ev=>{let b=ev.target.closest('[data-action]');if(!b)return;let a=b.dataset.action;if(pages.some(p=>p[0]===a))return go(a);if(a==='menu'){drawer=!drawer;render();return}if(a==='import')return importData();if(a==='run')return run();if(a==='approve')return approve();if(a==='release')return release();if(a==='reset'){modal={type:'reset'};render();return}if(a==='confirm-reset'){data.cycles[data.fund]=fresh(fund());save();modal=null;render();notify('Fund cycle reset.');return}if(a==='close'){modal=null;formError='';render();return}if(a.startsWith('fund:')){data.fund=a.slice(5);save();return go('overview')}if(a.startsWith('resolve:')){modal={type:'resolve',id:a.slice(8)};formError='';render();return}if(a.startsWith('report:'))return report(a.slice(7));if(a.startsWith('csv:'))return download(a.slice(4))});
document.addEventListener('submit',ev=>{if(ev.target.id==='inputs'){ev.preventDefault();saveInputs(ev.target)}if(ev.target.id==='resolution'){ev.preventDefault();resolve(modal.id,ev.target.elements.note.value)}});
document.addEventListener('input',ev=>{if(ev.target.id==='search'){query=ev.target.value;renderSearch()}});
document.addEventListener('change',ev=>{if(ev.target.id==='fund-select'){data.fund=ev.target.value;save();go('overview')}});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&(modal||drawer)){modal=null;drawer=false;formError='';render()}});
render();
